# ============================================================
# 🌍 TravelMundo IA - Cloud Build (v3.1.4)
# Deploy automático no Cloud Run (us-west1)
# Compatível com Gatilhos e Execuções Manuais ✅
# ============================================================

substitutions:
  _SERVICE_NAME: "travelmundo-api"
  _REGION: "us-west1"
  _VERSION: "3.1.4"

steps:
  # 🧩 1️⃣ Instalar dependências
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]

  # 🚀 2️⃣ Build da imagem Docker com tag de versão
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-west1-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/${_SERVICE_NAME}:latest",
        "-t",
        "us-west1-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/${_SERVICE_NAME}:${_VERSION}",
        "."
      ]

  # 📤 3️⃣ Envia imagem para o Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-west1-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/${_SERVICE_NAME}:latest"
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-west1-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/${_SERVICE_NAME}:${_VERSION}"
      ]

  # ☁️ 4️⃣ Deploy no Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "us-west1-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/${_SERVICE_NAME}:latest",
        "--region",
        "${_REGION}",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--memory",
        "512Mi",
        "--port",
        "8080",
        "--set-env-vars",
        "NODE_ENV=production,HOTMART_SECRET=TMIA_3v1_SECRET_2025"
      ]

# 🔐 Conta de serviço usada para o deploy
serviceAccount: "travelmundo-api-sa@gen-lang-client-0394942372.iam.gserviceaccount.com"

# ⏱️ Tempo máximo e destino dos logs
timeout: 900s
options:
  logging: CLOUD_LOGGING_ONLY
