# ============================================================
# 🌍 TravelMundo IA - Cloud Build (v3.1.7)
# 🔧 Deploy automatizado com variáveis e secret persistentes
# ============================================================

substitutions:
  _SERVICE_NAME: "travelmundo-api"
  _REGION: "us-west1"

steps:
  # 🧩 1️⃣ Instalar dependências
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]

  # 🚀 2️⃣ Build da imagem Docker
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-west1-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/${_SERVICE_NAME}:latest",
        "."
      ]

  # 📤 3️⃣ Envia imagem ao Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-west1-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/${_SERVICE_NAME}:latest"
      ]

  # ☁️ 4️⃣ Deploy no Cloud Run (com variáveis e Secret)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "us-west1-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/${_SERVICE_NAME}:latest",
        "--region",
        "${_REGION}",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--memory",
        "512Mi",
        "--port",
        "8080",
        "--set-env-vars",
        "NODE_ENV=production,HOTMART_SECRET=y4GJWDRbL1IXEOwXRwWN2G0GyQKkPJ22417386,GOOGLE_APPLICATION_CREDENTIALS=/etc/secrets/firebase-service-account",
        "--mount",
        "volume=firebase-key,source=projects/$PROJECT_ID/secrets/firebase-service-account,mode=0444,mount-path=/etc/secrets"
      ]

# 🔐 Conta de serviço usada para o deploy
serviceAccount: "travelmundo-api-sa@gen-lang-client-0394942372.iam.gserviceaccount.com"

timeout: 900s
options:
  logging: CLOUD_LOGGING_ONLY

